server:
  port: 8082
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rhms
    username: rhms
    password: "123456789"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
  application:
    name: rhms
