server:
  port: 8082
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rhms
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
  application:
    name: rhms
  cloud:
    compatibility-verifier:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://elaoumrani.com:8444/realms/SchoolManagement
  main:
    allow-bean-definition-overriding: true